remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
title: Bitcoin SQL sync
description: Synchronizes bitcoin-core node data with PostgreSQL database.
github:
  is_project_page: false
